"use client";

import { animate, motion, useInView, useMotionValue, useTransform } from "framer-motion";
import { useEffect, useRef } from "react";
import { Reveal } from "@/components/Reveal";

function StatCounter({ value, suffix = "" }: { value: number; suffix?: string }) {
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true, amount: 0.5 });
  const count = useMotionValue(0);
  const rounded = useTransform(count, (n) => Math.round(n));

  useEffect(() => {
    if (!inView) return;
    const controls = animate(count, value, { duration: 1.5 });
    return controls.stop;
  }, [count, inView, value]);

  return (
    <span ref={ref}>
      <motion.span>{rounded}</motion.span>
      {suffix}
    </span>
  );
}

export function AREProblem() {
  return (
    <section className="are-section border-y border-[var(--border-color)] bg-white py-20 md:py-24">
      <Reveal className="section-wrap">
        <h2 className="are-h2">
          Distribution is the hardest problem in business. Most brands are still
          solving it manually.
        </h2>

        <div className="mt-10 grid gap-6 md:grid-cols-3">
          <article className="are-card flex h-full flex-col bg-[#F5F6FA] p-8">
            <p className="mono bg-[linear-gradient(135deg,#00D2A0,#8B7BFF)] bg-clip-text text-6xl text-transparent">
              <StatCounter value={73} suffix="%" />
            </p>
            <p className="mt-3 text-[var(--text-primary)]">
              of sales rep time spent on non-selling activities
            </p>
            <p className="mt-2 text-xs text-[var(--text-faint)]">
              Salesforce State of Sales, 2026
            </p>
          </article>

          <article className="are-card flex h-full flex-col bg-[#F5F6FA] p-8">
            <p className="mono bg-[linear-gradient(135deg,#00D2A0,#8B7BFF)] bg-clip-text text-6xl text-transparent">
              <StatCounter value={6} suffix="x" />
            </p>
            <p className="mt-3 text-[var(--text-primary)]">
              more pipeline generated by AI-assisted outreach vs manual
            </p>
            <p className="mt-2 text-xs text-[var(--text-faint)]">
              McKinsey, 2025
            </p>
          </article>

          <article className="are-card flex h-full flex-col bg-[#F5F6FA] p-8">
            <p className="mono bg-[linear-gradient(135deg,#00D2A0,#8B7BFF)] bg-clip-text text-6xl text-transparent">
              <StatCounter value={40} suffix="%" />
            </p>
            <p className="mt-3 text-[var(--text-primary)]">
              of deals lost due to slow or inconsistent follow-up
            </p>
            <p className="mt-2 text-xs text-[var(--text-faint)]">
              Harvard Business Review
            </p>
          </article>
        </div>

        <p className="mt-10 text-center text-lg font-medium text-[var(--text-primary)]">
          "The problem isn't your product. It's that your distribution runs on
          humans — and humans don't scale."
        </p>
      </Reveal>
    </section>
  );
}
